name: node-ci

on:
  workflow_call:
    inputs:
      language:  {type: string,   required: true  }
      project:   { type: string,  default: roboshop }
      component: { type: string,  required: true }
      registry:  { type: string,  required: true }   # Floci ECR host (finalised in Phase 2)
      deploy:    { type: boolean, default: false }    # = booleanParam 'deploy'
    secrets:
       GITOPS_TOKEN: { required: false }               # PAT to push to the gitops repo
jobs:                                              #same as stages in jenkins
  ci:
    runs-on: srinivas-macbook-air
    timeout-minutes: 30
    concurrency: ${{inputs.component}}-ci
    env:
      AWS_ACCESS_KEY_ID: test                         # Floci dummy creds (replaces withAWS)
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localhost:4566
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: ver
        run: |
          case "${{ inputs.language }} in
            node) V= $(jq -r .Version package.json) ;;
            java)  java)   V=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) ;;
            go)     V="1.0.0" ;;
            python) V=$(cut -d= -f2 version.txt | tr -d '[:space:]') ;;
            *) echo "unknown language: ${{ inputs.language }}"; exit 1 ;;
          esac
          echo "Version: $V"
          echo "version=$V" >> "$GITHUB_OUTPUT"

      - name: Build / Install
        run: |
          case "${{ inputs.language }}" in
            node) npm install ;;
            java) mvn clean package ;;
            go) go mod tidy
            python) pip install -r requirements.txt ;;
          esac

      - name: Unit tests
        run: echo "unit tests go here (npm test / mvn test / go test / pytest)"

      - name: Build & push image
        env:
          IMG: ${{inputs.registry }}/${{inputs.project }}/${{inputs.component}};
        run: |
          aws ecr get-login-password --endpoint-url "$AWS_ENDPOINT_URL" \
            | docker login --username AWS --password-stdin "${{ inputs.registry }}"
          docker build -t "$IMG" .
          docker push "$IMG"
      - name: Bump image tag in GitOps repo          # replaces "Trigger deploy"
        if: ${{ inputs.deploy }}
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/bunnyrdy/roboshop-gitops.git gitops
          cd gitops
          yq -i '.image.tag = "${{ steps.ver.outputs.version }}"' charts/${{ inputs.component }}/values.yaml
          git config user.name  "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git commit -am "ci: ${{ inputs.component }} -> ${{ steps.ver.outputs.version }}"
          git push
      
      
